<?php

namespace Azgil\CategoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryTreeRepository extends EntityRepository {

    public function findOneByIdJoinedToCategoryNode($id) {
        $query = $this->getEntityManager()
                        ->createQuery('
            SELECT t, n FROM AzgilCategoryBundle:CategoryTree t
            JOIN t.node n
            WHERE t.id = :id'
                        )->setParameter('id', $id);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    public function findAllJoinedToCategoryNode($type) {
        $query = $this->getEntityManager()
                ->createQuery('
            SELECT t, n FROM AzgilCategoryBundle:CategoryTree t
            JOIN t.node n
            ORDER BY t.type ASC'
        );

        try {
            return $query->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

}
