<?php

namespace Azgil\CategoryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryTypeRepository extends EntityRepository
{
}
