<?php

namespace Azgil\GalleryBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CatRelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatRelRepository extends EntityRepository
{
}
